### ISSUE TITLE
Index sorting

### ISSUE THREAD

**Issue by jeandav** [paintedsky/dead-simple-blog#6]
Hi people,

For some reasons, I can't find the logic in the way the index is sorted. In my case it is not chronological nor alphabetical, nor following any logic. Is there any way to fix this ?

Thanks in advance,

**Comment by paintedsky** [comment]
Hi,

Yeah at the moment there isn't really any custom sorting. It uses [DirectoryIterator](https://www.php.net/manual/en/class.directoryiterator.php) to get the files from the ./content/ directory. DirectoryIterator doesn't accept any sorting parameters - it simply lists the files in the same order that you'd get them from a "ls -l" command on the command line. This should be alphabetical by default if I'm not mistaken.

In my case, I use YYYY-MM-DD date-based names (e.g. 2018-10-30.txt). This worked well for me, but if you want to use a different naming convention it might not work for you.

The way to fix this is to load the files into an array before outputting them, and sort the array. [See this link](https://stackoverflow.com/a/18337742) for more details on that.

Your suggestion to have sorting makes sense, so I wouldn't be opposed to updating this to include it. However, it may take some time for me to get around to making that update, so if you'd prefer not to wait and would like to make a pull request instead, please feel free to do so.

Thanks!

**Comment by paintedsky** [comment]
Closing this as version 1.1 now explicitly sorts posts. Default is sorting by filename (descending) but the code can be easily modified to sort by different file attributes, in either direction.
